menu:
  Home: /
  Archives: /archives
  About Me: /about

widgets:
- search
- tag
- weibo

excerpt_link: continue

twitter:
  username: ClassicShuang
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  # facebook: true
  # twitter: true
  # google: true
  # pinterest: true

fancybox: true

google_analytics:
rss: /atom.xml